# --------------------------- #
# 设置部分
# --------------------------- #
SETTINGS:
    # 并发线程数
    THREADS: 1
    # 任何操作的重试次数
    ATTEMPTS: 3
    # 账户范围
    # 默认值: [0, 0] - 所有账户
    # [3, 5] - 仅使用 3、4、5 号账户
    # [7, 7] - 仅使用 7 号账户
    ACCOUNTS_RANGE: [0, 0]
    # 仅当 ACCOUNTS_RANGE 为 [0, 0] 时生效
    # 指定要使用的账户
    # 默认值: [] - 所有账户
    # 示例: [1, 4, 6] - 机器人将仅使用 1、4 和 6 号账户
    EXACT_ACCOUNTS_TO_USE: []
    # 重试之间的暂停时间
    PAUSE_BETWEEN_ATTEMPTS: [5, 15]
    # 交换操作之间的暂停时间
    PAUSE_BETWEEN_SWAPS: [10, 40]
    # 账户之间的随机暂停时间（秒）
    RANDOM_PAUSE_BETWEEN_ACCOUNTS: [3, 15]
    # 操作之间的随机暂停时间（秒）
    RANDOM_PAUSE_BETWEEN_ACTIONS: [3, 10]
    # 每个账户启动前的随机暂停时间
    # 确保所有账户在不同时间启动
    RANDOM_INITIALIZATION_PAUSE: [5, 30]
    # 浏览器操作的暂停时间倍数
    BROWSER_PAUSE_MULTIPLIER: 1.5
    # Telegram 设置
    TELEGRAM_BOT_TOKEN: ''
    TELEGRAM_USERS_IDS: []

# --------------------------- #
# 流程部分
# --------------------------- #
FLOW:
    # 交换次数（bean、ambient、monad 等）
    NUMBER_OF_SWAPS: [1, 1]
    # 要交换的余额百分比
    PERCENT_OF_BALANCE_TO_SWAP: [10, 15]

# --------------------------- #
# 其他部分
# --------------------------- #
DISPERSE:
    # 如果主账户余额小于此值
    # 机器人将从挖矿账户向主账户分发代币
    MIN_BALANCE_FOR_DISPERSE: [0.4, 0.5]

DUSTED:
    CLAIM: true  # 或 false 以禁用领取奖励
    SKIP_TWITTER_VERIFICATION: false

APRIORI:
    AMOUNT_TO_STAKE: [0.0001, 0.0003]
    STAKE: true
    UNSTAKE: true

MAGMA:
    AMOUNT_TO_STAKE: [0.0001, 0.0003]
    STAKE: true
    UNSTAKE: true

KINTSU:
    # 最小值为 0.01 $MON
    AMOUNT_TO_STAKE: [0.01, 0.02]
    STAKE: true
    UNSTAKE: true

BIMA:
    LEND: true
    PERCENT_OF_BALANCE_TO_LEND: [20.0, 30.0]

GASZIP:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Base", "Optimism"]
    AMOUNT_TO_REFUEL: [0.0001, 0.00015]
    MINIMUM_BALANCE_TO_REFUEL: 0.5
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999
    BRIDGE_ALL: false
    BRIDGE_ALL_MAX_AMOUNT: 0.01

MEMEBRIDGE:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Base", "Optimism"]
    AMOUNT_TO_REFUEL: [0.0001, 0.00015]
    MINIMUM_BALANCE_TO_REFUEL: 0.5
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999
    BRIDGE_ALL: false
    BRIDGE_ALL_MAX_AMOUNT: 0.01

TESTNET_BRIDGE:
    NETWORKS_TO_REFUEL_FROM: ["Arbitrum", "Optimism"]
    AMOUNT_TO_REFUEL: [0.0002, 0.0003]
    MINIMUM_BALANCE_TO_REFUEL: 5.0
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999
    BRIDGE_ALL: false
    BRIDGE_ALL_MAX_AMOUNT: 0.01

NOSTRA:
    PERCENT_OF_BALANCE_TO_DEPOSIT: [3, 15]
    DEPOSIT: true
    BORROW: true
    REPAY: true
    WITHDRAW: true

SHMONAD:
    BUY_AND_STAKE_SHMON: true
    UNSTAKE_AND_SELL_SHMON: true
    # shmonad.xyz 上要交换的余额百分比
    PERCENT_OF_BALANCE_TO_SWAP: [2, 3]

ACCOUNTABLE:
    NFT_PER_ACCOUNT_LIMIT: 3

ORBITER:
    AMOUNT_TO_BRIDGE: [0.1, 0.2]
    BRIDGE_ALL: true
    WAIT_FOR_FUNDS_TO_ARRIVE: true
    MAX_WAIT_TIME: 999999999

LILCHOGSTARS:
    MAX_AMOUNT_FOR_EACH_ACCOUNT: [1, 3]

DEMASK:
    MAX_AMOUNT_FOR_EACH_ACCOUNT: [1, 3]

# monadking 或 monadking_unlocked
MONADKING:
    MAX_AMOUNT_FOR_EACH_ACCOUNT: [1, 3]

FRONT_RUNNER:
    MAX_AMOUNT_TRANSACTIONS_FOR_ONE_RUN: [1, 3]
    PAUSE_BETWEEN_TRANSACTIONS: [10, 30]

MAGICEDEN:
    NFT_CONTRACTS: [
        "0x9e313cbd57a35661072c1b96684454cebd09acdc"
    ]

FAUCET:
    USE_SOLVIUM_FOR_CLOUDFLARE: true
    # 最便宜的验证码解决方案 - https://t.me/solvium_crypto_bot
    SOLVIUM_API_KEY: sadfhasldfhalsdjfhalsdjf

    # 可选
    USE_CAPSOLVER_FOR_CLOUDFLARE: false
    CAPSOLVER_API_KEY: CAP-asdfasldjkfashdfadhasd

    # 默认使用 Nocaptcha
    NOCAPTCHA_API_KEY: abc
    # 如果没有代理无法工作，在这里设置代理
    # 格式: username:password@ip:port
    PROXY_FOR_NOCAPTCHA: ""
    
# --------------------------- #
# 交易所部分
# --------------------------- #
EXCHANGES:
    name: "OKX"  # 支持: "OKX", "BITGET"
    apiKey: ''
    secretKey: ''
    passphrase: ''  
    withdrawals:
        - currency: "ETH" # 仅支持 ETH
          networks: ["Arbitrum", "Base", "Optimism"] # ["Arbitrum", "Base", "Optimism"]
          min_amount: 0.0003
          max_amount: 0.0004
          max_balance: 0.005
          wait_for_funds: true
          max_wait_time: 99999  # 单位：秒
          retries: 3

